openapi: 3.0.0
info:
  title: Order Management API
  description: API for managing orders in the coffee store application.
  version: 1.0.0
tags:
  - name: Orders
    description: Order management

paths:
  /orders:
    post:
      summary: Create a new order
      tags:
        - Orders
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                storeId:
                  type: integer
                shipping_address:
                  type: string
                discount:
                  type: number
                  format: float
      responses:
        "201":
          description: Order created successfully
        "400":
          description: Bad request
        "500":
          description: Server error

  /orders/{orderId}:
    post:
      summary: Add an item to an existing order
      tags:
        - Orders
      security:
        - bearerAuth: []
      parameters:
        - name: orderId
          in: path
          required: true
          description: ID of the order to add the item to
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: integer
                quantity:
                  type: integer
                ristretto:
                  type: string
                isOnsite:
                  type: boolean
                size:
                  type: string
                time_prepare:
                  type: string
                prepare_time:
                  type: string
      responses:
        "201":
          description: Order item added successfully
        "400":
          description: Bad request
        "404":
          description: Order not found
        "500":
          description: Server error
