openapi: 3.0.0
info:
  title: Order Management API
  description: API for managing orders
  version: 1.0.0
tags:
  - name: Orders
    description: Orders management

paths:
  /orders:
    post:
      summary: Create a new order
      tags:
        - Orders
      security:
        - bearerAuth: []  # Thêm xác thực token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
                  description: ID of the user placing the order
                storeId:
                  type: integer
                  description: ID of the store where the order is placed
                orderItems:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: integer
                        description: The product ID
                shipping_address:
                  type: string
                  description: Shipping address for the order
                discount:
                  type: number
                  format: float
                  description: Discount applied to the order
                  default: 0.0
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  order:
                    type: object
                    properties:
                      userId:
                        type: integer
                      storeId:
                        type: integer
                      shipping_address:
                        type: string
                      discount:
                        type: number
                        format: float
                      total_price:
                        type: number
                        format: float
                      orderItems:
                        type: array
                        items:
                          type: object
                          properties:
                            productId:
                              type: integer
                            productName:
                              type: string
                            productImage:
                              type: string
                            quantity:
                              type: integer
                            ristretto:
                              type: string
                              enum: [NONE, SMALL, MEDIUM, LARGE]
                            size:
                              type: string
                              enum: [SMALL, MEDIUM, LARGE]
                            total_amount:
                              type: number
                              format: float
        '400':
          description: Bad request due to validation error
        '404':
          description: One or more OrderItems not found
        '500':
          description: Server error
