openapi: 3.0.0
info:
  title: Order Item Management API
  description: API for managing order items
  version: 1.0.0
tags:
  - name: OrderItems
    description: Order items management

paths:
  /order-items:
    post:
      summary: Create a new order item
      tags:
        - OrderItems
      security:
        - bearerAuth: []  # Thêm xác thực token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                productId:
                  type: integer
                  description: The product ID for the order item
                quantity:
                  type: integer
                  description: The quantity of the product
                ristretto:
                  type: string
                  enum: [NONE, SMALL, MEDIUM, LARGE]
                  description: Ristretto level
                isOnsite:
                  type: boolean
                  description: Whether the order is for onsite consumption
                size:
                  type: string
                  enum: [SMALL, MEDIUM, LARGE]
                  description: Size of the product
                time_prepare:
                  type: integer
                  description: Preparation time for the product
                prepare_time:
                  type: integer
                  description: Time required for preparing the product
      responses:
        '201':
          description: Order item created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  orderItem:
                    type: object
                    properties:
                      productId:
                        type: integer
                      productName:
                        type: string
                      productImage:
                        type: string
                      quantity:
                        type: integer
                      ristretto:
                        type: string
                        enum: [NONE, SMALL, MEDIUM, LARGE]
                      size:
                        type: string
                        enum: [SMALL, MEDIUM, LARGE]
                      total_amount:
                        type: number
        '400':
          description: Bad request due to validation error or product not found
        '500':
          description: Server error
