openapi: 3.0.0
info:
  title: User Management API
  description: API for managing users
  version: 1.0.0
tags:
  - name: Users
    description: User management

paths:
  /users/register:
    post:
      summary: Register a new user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                phone:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: User registered successfully
        "400":
          description: Email already exists.
        "500":
          description: Server error

  /users/login:
    post:
      summary: Login an existing user
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful
        "401":
          description: Email or password is incorrect
        "500":
          description: Server error

  /users/forgot-password:
    post:
      summary: Request password reset OTP
      tags:
        - Users
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
      responses:
        "200":
          description: OTP code has been sent to your email
        "404":
          description: No user found with this email
        "500":
          description: Server error

  /users/verify-otp:
    post:
      summary: Verify OTP
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                otp_code:
                  type: string
      responses:
        "200":
          description: OTP has been successfully authenticated.
        "400":
          description: OTP is invalid or has already been used
        "401":
          description: OTP is incorrect. Try again.
        "500":
          description: Server error

  /users/reset-password:
    post:
      summary: Reset password using verified OTP
      tags:
        - Users
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                newPassword:
                  type: string
                confirmPassword:
                  type: string
      responses:
        "200":
          description: Password updated successfully
        "400":
          description: Confirm password must be same as new password
        "401":
          description: Missing or invalid token authenticated.
        "403":
          description: Token invalid or expired
        "500":
          description: Server error
